const bikes = [ 
                {
                  infernoID: '000001',
                  manufacturer: 'Co-op',
                  model: '',
                  serialNumber: 'U205K00053',
                  color: 'Grey',
                  drivetrain:'3x',
                  fork: '',
                  location: 'Ryan',
                  status: 'Storage',
                  size: 'S',
                  wheelSize: '',
                  notes: 'New rear tire, cut bars, pedals, tune up'
                },
                {
                  infernoID: '000002',
                  manufacturer: 'Specialized',
                  model: '',
                  serialNumber: '',
                  color: 'Black/Orange',
                  drivetrain:'',
                  fork: '',
                  location: 'Ryan',
                  status: 'Storage',
                  size: '',
                  wheelSize: '',
                  notes: 'Forks off Andy'
                },
                {
                  infernoID: '000003',
                  manufacturer: 'Trek',
                  model: 'Marlin 6',
                  serialNumber: 'WTU191C1196J',
                  color: 'Black/Green',
                  drivetrain:'1x',
                  fork: 'Suntour SR XC',
                  location: 'Matt',
                  status: 'Storage',
                  size: 'M',
                  wheelSize: '29',
                  notes: 'Change stem and pedals'
                },
                {
                  infernoID: '000004',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000005',
                  manufacturer: 'Specialized',
                  model: 'Rockhopper',
                  serialNumber: '',
                  frameSerialNumber: 'WSBxx0111',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: 'Shrek',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000006',
                  manufacturer: 'Specialized',
                  model: '',
                  serialNumber: 'WSBO0112664985',
                  color: 'Red',
                  drivetrain:'2x',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: 'M',
                  wheelSize: '29'
                },
                {
                  infernoID: '000007',
                  manufacturer: 'Trek',
                  model: 'Marlin 6',
                  serialNumber: 'WTU013C0265N',
                  color: 'Black/Silver',
                  drivetrain:'1x9',
                  fork: '',
                  location: 'Shrek',
                  status: 'Storage',
                  size: '',
                  wheelSize: '',
                  notes: 'Wolftooth to move to Giant Talon 008'
                },
                {
                  infernoID: '000008',
                  manufacturer: 'Giant',
                  model: 'Talon',
                  serialNumber: 'C1CD4146',
                  frameSerialNumber: 'K6EK12802',
                  color: 'Black/Green',
                  drivetrain:'3x',
                  fork: '',
                  location: 'Shrek',
                  status: 'Storage',
                  size: '',
                  wheelSize: '',
                  notes: 'Replace the drivetrain with 1x from 007'
                },
                {
                  infernoID: '000009',
                  manufacturer: 'Trek',
                  model: 'Marlin',
                  serialNumber: 'WTU360C1030M',
                  frameSerialNumber: '2039U0315',
                  color: 'Silver',
                  drivetrain:'1x',
                  fork: '',
                  location: 'Shrek',
                  status: 'Storage',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000010',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000011',
                  manufacturer: 'Specialized',
                  model: '',
                  serialNumber: '',
                  color: 'Black/Green',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000012',
                  manufacturer: 'Specialized',
                  model: 'Pitch',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: 'Ryan',
                  status: 'Storage',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000013',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000014',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000015',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000016',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  status: 'Storage',
                  size: '',
                  wheelSize: ''
                },
];

module.exports =  {bikes};