const bikes = [ 
                {
                  infernoID: '000001',
                  manufacturer: 'Co-op',
                  model: '',
                  serialNumber: 'U205K00053',
                  color: 'Grey',
                  drivetrain:'3x',
                  fork: '',
                  location: 'Ryan',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000002',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000003',
                  manufacturer: 'Trek',
                  model: 'Marlin 6',
                  serialNumber: 'WTU191C1196J',
                  color: 'Black/Green',
                  drivetrain:'1x',
                  fork: 'Suntour SR XC',
                  location: 'Shrek',
                  size: 'M',
                  wheelSize: '29'
                },
                {
                  infernoID: '000004',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000005',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000006',
                  manufacturer: 'Specialized',
                  model: '',
                  serialNumber: 'WSBO0112664985',
                  color: 'Red',
                  drivetrain:'2x',
                  fork: '',
                  location: '',
                  size: 'M',
                  wheelSize: '29'
                },
                {
                  infernoID: '000007',
                  manufacturer: 'Trek',
                  model: 'Marlin',
                  serialNumber: '',
                  color: 'Black',
                  drivetrain:'',
                  fork: '',
                  location: 'Shrek',
                  size: '',
                  wheelSize: '',
                  notes: 'Wolftooth to move to Giant Talon 008'
                },
                {
                  infernoID: '000008',
                  manufacturer: 'Giant',
                  model: 'Talon',
                  serialNumber: 'C1CD4146',
                  color: 'Black/Green',
                  drivetrain:'3x',
                  fork: '',
                  location: 'Shrek',
                  size: '',
                  wheelSize: '',
                  notes: 'Replace the drivetrain with 007'
                },
                {
                  infernoID: '000009',
                  manufacturer: 'Trek',
                  model: 'Marlin',
                  serialNumber: 'WTU360C1030M',
                  color: 'Silver',
                  drivetrain:'1x',
                  fork: '',
                  location: 'Shrek',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000010',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000011',
                  manufacturer: 'Specialized',
                  model: '',
                  serialNumber: '',
                  color: 'Black/Green',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000012',
                  manufacturer: 'Specialized',
                  model: 'Pitch',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: 'Ryan',
                  size: 'S',
                  wheelSize: ''
                },
                {
                  infernoID: '000013',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000014',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000015',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
                {
                  infernoID: '000016',
                  manufacturer: '',
                  model: '',
                  serialNumber: '',
                  color: '',
                  drivetrain:'',
                  fork: '',
                  location: '',
                  size: '',
                  wheelSize: ''
                },
];

module.exports =  {bikes};